import {
    Activity,
    AlertCircle,
    AlertTriangle,
    ArrowDown,
    ArrowDownRight,
    ArrowUp,
    ArrowUpRight,
    Book,
    BookOpen,
    Calendar,
    ChartBar,
    ChartColumn,
    Check,
    CheckCircle2,
    ChevronDown,
    Circle,
    Clock,
    Copy,
    CreditCard,
    DollarSign,
    Download,
    Edit3,
    Eye,
    ExternalLink,
    Filter,
    Info,
    Link,
    Mail,
    MoreVertical,
    Package,
    Pencil,
    Percent,
    Phone,
    Plus,
    RotateCcw,
    Settings,
    ShoppingBag,
    ShoppingCart,
    SlidersHorizontal,
    Star,
    Unlink,
    Trash2,
    TrendingDown,
    TrendingUp,
    Upload,
    User,
    Users,
    Wallet,
    X,
    XCircle,
} from '@lucide/vue';
import type { Component } from 'vue';

/**
 * Shared Lucide icon map for Kinetix actions/columns. Single source of truth so
 * every action-rendering component (table, dropdown, page header) resolves the
 * same names — prevents "missing icon" drift when prebuilt actions add icons.
 *
 * Names mirror the kebab-case strings actions/columns set via `->icon('name')`.
 */
const ICONS: Record<string, Component> = {
    edit: Edit3,
    pencil: Pencil,
    delete: Trash2,
    trash: Trash2,
    'trash-2': Trash2,
    view: Eye,
    eye: Eye,
    create: Plus,
    plus: Plus,
    download: Download,
    upload: Upload,
    restore: RotateCcw,
    'rotate-ccw': RotateCcw,
    settings: Settings,
    filter: Filter,
    'sliders-horizontal': SlidersHorizontal,
    'ellipsis-vertical': MoreVertical,
    'more-vertical': MoreVertical,
    'chevron-down': ChevronDown,
    'arrow-up': ArrowUp,
    'arrow-down': ArrowDown,
    check: Check,
    'check-circle': CheckCircle2,
    x: X,
    'x-circle': XCircle,
    circle: Circle,
    star: Star,
    copy: Copy,
    link: Link,
    unlink: Unlink,
    'external-link': ExternalLink,
    mail: Mail,
    phone: Phone,
    calendar: Calendar,
    user: User,
    users: Users,
    info: Info,
    'credit-card': CreditCard,
    // Dashboard / widget icons
    'dollar-sign': DollarSign,
    wallet: Wallet,
    'shopping-cart': ShoppingCart,
    'shopping-bag': ShoppingBag,
    package: Package,
    cube: Package,
    box: Package,
    clock: Clock,
    activity: Activity,
    'alert-circle': AlertCircle,
    'alert-triangle': AlertTriangle,
    'trending-up': TrendingUp,
    'trending-down': TrendingDown,
    'arrow-up-right': ArrowUpRight,
    'arrow-down-right': ArrowDownRight,
    percent: Percent,
    book: Book,
    'book-open': BookOpen,
    'chart-bar': ChartBar,
    'chart-column': ChartColumn,
    'bar-chart': ChartColumn,
};

/**
 * Resolve a Lucide icon component by name. Returns null for empty/unknown names
 * so callers can simply guard with `v-if`.
 */
export function resolveIcon(name?: string | null): Component | null {
    if (!name) {
        return null;
    }

    return ICONS[name.toLowerCase()] ?? null;
}
