<script setup lang="ts">
import { withBase } from "vitepress";

/**
 * Renders a component screenshot that follows the site's light/dark theme:
 * shows `<name>.png` in light mode and `<name>-dark.png` in dark mode. Images
 * live in docs/public/screenshots and are generated by `npm run screenshots`.
 */
const props = defineProps<{ name: string; alt?: string }>();
</script>

<template>
  <span class="kx-shot">
    <img
      class="kx-shot-light"
      :src="withBase(`/screenshots/${props.name}.png`)"
      :alt="props.alt ?? props.name"
      loading="lazy"
    />
    <img
      class="kx-shot-dark"
      :src="withBase(`/screenshots/${props.name}-dark.png`)"
      :alt="props.alt ?? props.name"
      loading="lazy"
    />
  </span>
</template>
