/**
 * Stub of @/composables/useKinetixHttp for the gallery. `kinetixFetch` returns
 * canned fixtures based on the URL so self-fetching components (e.g. the
 * onboarding checklist) render fully without a backend.
 */
const col = (name: string, extra: Record<string, unknown> = {}) => ({
    name,
    label: name.charAt(0).toUpperCase() + name.slice(1),
    isSearchable: false,
    isSortable: false,
    alignment: 'left',
    isToggleable: false,
    isToggledHiddenByDefault: false,
    type: 'text',
    ...extra,
});

const fixtures: Array<{ match: RegExp; data: unknown }> = [
    {
        match: /\/mail-templates\/preview$/,
        data: {
            subject: 'Welcome to Acme, Ada!',
            html: '<h1>Hi Ada 👋</h1><p>Thanks for joining Acme. Your trial ends on <strong>July 15</strong>.</p><p><a href="#">Get started →</a></p>',
        },
    },
    {
        match: /\/mail-templates$/,
        data: {
            templates: [
                {
                    id: 1,
                    key: 'welcome',
                    name: 'Welcome email',
                    subject: 'Welcome to Acme, {{ name }}!',
                    body: '# Hi {{ name }} 👋\n\nThanks for joining Acme. Your trial ends on **{{ trial_ends }}**.\n\n[Get started →](#)',
                    format: 'markdown',
                    variables: [
                        { key: 'name', label: 'Name', sample: 'Ada' },
                        {
                            key: 'trial_ends',
                            label: 'Trial end',
                            sample: 'July 15',
                        },
                    ],
                    enabled: true,
                },
                {
                    id: 2,
                    key: 'receipt',
                    name: 'Order receipt',
                    subject: 'Your receipt #{{ order }}',
                    body: 'Thanks for your order **#{{ order }}** — total {{ total }}.',
                    format: 'markdown',
                    variables: [],
                    enabled: true,
                },
                {
                    id: 3,
                    key: 'password-reset',
                    name: 'Password reset',
                    subject: 'Reset your password',
                    body: '<p>Click to reset.</p>',
                    format: 'html',
                    variables: [],
                    enabled: false,
                },
            ],
        },
    },
    {
        match: /\/health$/,
        data: {
            available: true,
            status: 'warning',
            checkedAt: '2026-06-27T10:00:00Z',
            checks: [
                {
                    name: 'database',
                    label: 'Database',
                    status: 'ok',
                    message: 'Reachable',
                },
                {
                    name: 'cache',
                    label: 'Cache',
                    status: 'ok',
                    message: 'Working',
                },
                { name: 'redis', label: 'Redis', status: 'ok', message: null },
                {
                    name: 'disk',
                    label: 'Used Disk Space',
                    status: 'warning',
                    message: 'Disk usage at 85%',
                },
                {
                    name: 'queue',
                    label: 'Queue',
                    status: 'ok',
                    message: 'Default queue healthy',
                },
            ],
        },
    },
    {
        match: /\/queue$/,
        data: {
            horizon: true,
            status: 'running',
            throughput: 128,
            recentJobs: 4200,
            failedJobs: 2,
            failed: [
                {
                    id: 'a1b2',
                    connection: 'redis',
                    queue: 'emails',
                    name: 'SendInvoiceEmail',
                    failedAt: '2026-06-27T09:14:00Z',
                },
                {
                    id: 'c3d4',
                    connection: 'redis',
                    queue: 'exports',
                    name: 'GenerateReport',
                    failedAt: '2026-06-27T08:02:00Z',
                },
            ],
            queues: [
                { name: 'default', connection: null, size: 12, wait: 3 },
                { name: 'emails', connection: null, size: 4, wait: 1 },
                { name: 'exports', connection: null, size: 0, wait: 0 },
            ],
        },
    },
    {
        match: /\/tokens$/,
        data: {
            tokens: [
                {
                    id: 1,
                    name: 'CI deploy',
                    abilities: ['posts.read', 'posts.write'],
                    lastUsedAt: '2026-06-20T10:00:00Z',
                    createdAt: '2026-06-01T09:00:00Z',
                    expiresAt: '2026-12-31T23:59:59Z',
                },
                {
                    id: 2,
                    name: 'Zapier',
                    abilities: ['*'],
                    lastUsedAt: null,
                    createdAt: '2026-06-18T14:30:00Z',
                    expiresAt: null,
                },
                {
                    id: 3,
                    name: 'Legacy import',
                    abilities: ['posts.read'],
                    lastUsedAt: '2026-01-05T08:00:00Z',
                    createdAt: '2025-11-01T08:00:00Z',
                    expiresAt: '2026-02-01T00:00:00Z',
                },
            ],
            scopes: {
                'posts.read': 'Read posts',
                'posts.write': 'Write posts',
            },
        },
    },
    {
        match: /\/webhooks$/,
        data: {
            endpoints: [
                {
                    id: 1,
                    name: 'Order events',
                    url: 'https://example.com/hooks/orders',
                    events: ['order.created', 'order.shipped'],
                    active: true,
                    createdAt: '2026-06-10T09:00:00Z',
                },
                {
                    id: 2,
                    name: 'Billing sync',
                    url: 'https://example.com/hooks/billing',
                    events: ['invoice.paid'],
                    active: false,
                    createdAt: '2026-06-12T11:00:00Z',
                },
            ],
            events: {
                'order.created': 'Order created',
                'order.shipped': 'Order shipped',
                'invoice.paid': 'Invoice paid',
            },
        },
    },
    {
        match: /\/activity$/,
        data: {
            data: [
                {
                    id: 1,
                    event: 'updated',
                    description: null,
                    causerName: 'Ada Lovelace',
                    causerId: 1,
                    subjectType: 'Order',
                    subjectId: 1042,
                    changes: {
                        old: { status: 'pending' },
                        attributes: { status: 'paid' },
                    },
                    createdAt: '2026-06-20T10:00:00Z',
                },
                {
                    id: 2,
                    event: 'created',
                    description: null,
                    causerName: 'Grace Hopper',
                    causerId: 2,
                    subjectType: 'Order',
                    subjectId: 1043,
                    changes: { old: {}, attributes: {} },
                    createdAt: '2026-06-19T16:30:00Z',
                },
            ],
            pagination: { current_page: 1, last_page: 1 },
        },
    },
    {
        match: /\/pdf-templates\/quote$/,
        data: {
            key: 'quote',
            label: 'Quotation',
            hasLogo: false,
            fields: [
                {
                    name: 'accent',
                    type: 'color',
                    label: 'Accent color',
                    default: '#6366f1',
                    help: null,
                    palette: [
                        '#6366f1',
                        '#8b5cf6',
                        '#0ea5e9',
                        '#10b981',
                        '#f59e0b',
                        '#ef4444',
                        '#ec4899',
                        '#0f172a',
                    ],
                    options: {},
                    maxLength: null,
                },
                {
                    name: 'font',
                    type: 'select',
                    label: 'Typography',
                    default: 'sans',
                    help: null,
                    palette: [],
                    options: { sans: 'Sans', serif: 'Serif' },
                    maxLength: null,
                },
                {
                    name: 'doc_title',
                    type: 'text',
                    label: 'Document title',
                    default: 'Quotation',
                    help: null,
                    palette: [],
                    options: {},
                    maxLength: 60,
                },
                {
                    name: 'striped',
                    type: 'toggle',
                    label: 'Striped rows',
                    default: true,
                    help: null,
                    palette: [],
                    options: {},
                    maxLength: null,
                },
                {
                    name: 'signature',
                    type: 'toggle',
                    label: 'Signature line',
                    default: false,
                    help: null,
                    palette: [],
                    options: {},
                    maxLength: null,
                },
            ],
            settings: {
                accent: '#6366f1',
                font: 'sans',
                doc_title: 'Quotation',
                striped: true,
                signature: false,
            },
            defaults: {
                accent: '#6366f1',
                font: 'sans',
                doc_title: 'Quotation',
                striped: true,
                signature: false,
            },
        },
    },
    {
        match: /\/webhooks\/logs/,
        data: {
            data: [
                {
                    id: 1,
                    event: 'order.created',
                    statusCode: 200,
                    success: true,
                    attempt: 1,
                    createdAt: '2026-07-10T10:04:00Z',
                    payload: { order_id: 981, total: '129.90' },
                    response: '{"ok":true}',
                    endpointName: 'Billing hook',
                    endpointUrl: 'https://api.acme.dev/hooks/billing',
                },
                {
                    id: 2,
                    event: 'invoice.paid',
                    statusCode: 500,
                    success: false,
                    attempt: 3,
                    createdAt: '2026-07-10T09:58:00Z',
                    payload: { invoice_id: 'inv_204' },
                    response: 'Server error',
                    endpointName: 'ERP sync',
                    endpointUrl: 'https://erp.acme.dev/webhooks',
                },
                {
                    id: 3,
                    event: 'order.shipped',
                    statusCode: 200,
                    success: true,
                    attempt: 1,
                    createdAt: '2026-07-10T09:41:00Z',
                    payload: { order_id: 975 },
                    response: '{"ok":true}',
                    endpointName: 'Billing hook',
                    endpointUrl: 'https://api.acme.dev/hooks/billing',
                },
            ],
            pagination: { current_page: 1, last_page: 4, total: 58 },
        },
    },
    {
        match: /\/api-logs/,
        data: {
            data: [
                {
                    id: 11,
                    method: 'GET',
                    path: '/api/v1/orders',
                    status: 200,
                    durationMs: 24,
                    tokenName: 'Zapier',
                    ip: '34.12.0.8',
                    requestBody: null,
                    responseBody: null,
                    createdAt: '2026-07-10T10:05:00Z',
                },
                {
                    id: 12,
                    method: 'POST',
                    path: '/api/v1/orders',
                    status: 422,
                    durationMs: 41,
                    tokenName: 'CI bot',
                    ip: '10.0.0.9',
                    requestBody: { sku: 'A-1', qty: 2 },
                    responseBody: '{"message":"The sku is invalid."}',
                    createdAt: '2026-07-10T10:02:00Z',
                },
                {
                    id: 13,
                    method: 'DELETE',
                    path: '/api/v1/orders/975',
                    status: 204,
                    durationMs: 18,
                    tokenName: 'Zapier',
                    ip: '34.12.0.8',
                    requestBody: null,
                    responseBody: null,
                    createdAt: '2026-07-10T09:47:00Z',
                },
            ],
            pagination: { current_page: 1, last_page: 2, total: 23 },
        },
    },
    {
        match: /\/permissions\/features$/,
        data: [
            {
                name: 'users',
                label: 'Users',
                abilities: [
                    {
                        key: 'viewAny',
                        label: 'List',
                        permission: 'users.viewAny',
                    },
                    { key: 'view', label: 'View', permission: 'users.view' },
                    {
                        key: 'create',
                        label: 'Create',
                        permission: 'users.create',
                    },
                    {
                        key: 'update',
                        label: 'Update',
                        permission: 'users.update',
                    },
                    {
                        key: 'delete',
                        label: 'Delete',
                        permission: 'users.delete',
                    },
                ],
            },
            {
                name: 'orders',
                label: 'Orders',
                abilities: [
                    {
                        key: 'viewAny',
                        label: 'List',
                        permission: 'orders.viewAny',
                    },
                    { key: 'view', label: 'View', permission: 'orders.view' },
                    {
                        key: 'update',
                        label: 'Update',
                        permission: 'orders.update',
                    },
                    {
                        key: 'refund',
                        label: 'Refund',
                        permission: 'orders.refund',
                    },
                ],
            },
            {
                name: 'reports',
                label: 'Reports',
                abilities: [
                    {
                        key: 'viewAny',
                        label: 'List',
                        permission: 'reports.viewAny',
                    },
                    {
                        key: 'create',
                        label: 'Create',
                        permission: 'reports.create',
                    },
                ],
            },
        ],
    },
    {
        match: /\/permissions\/roles$/,
        data: [
            {
                id: 1,
                name: 'admin',
                usersCount: 3,
                permissions: [
                    'users.viewAny',
                    'users.view',
                    'users.create',
                    'users.update',
                    'users.delete',
                    'orders.viewAny',
                    'orders.view',
                    'orders.update',
                    'orders.refund',
                    'reports.viewAny',
                    'reports.create',
                ],
            },
            {
                id: 2,
                name: 'editor',
                usersCount: 8,
                permissions: [
                    'users.viewAny',
                    'users.view',
                    'orders.viewAny',
                    'orders.view',
                ],
            },
            {
                id: 3,
                name: 'viewer',
                usersCount: 21,
                permissions: ['users.viewAny', 'orders.viewAny'],
            },
        ],
    },
    {
        match: /\/members$/,
        data: {
            provisions: [
                {
                    id: 1,
                    email: 'ada@example.com',
                    name: 'Ada Lovelace',
                    role: 'editor',
                    status: 'active',
                    expired: false,
                    activatedAt: '2026-06-10T09:00:00Z',
                    expiresAt: null,
                },
                {
                    id: 2,
                    email: 'grace@example.com',
                    name: null,
                    role: 'viewer',
                    status: 'pending',
                    expired: false,
                    activatedAt: null,
                    expiresAt: '2026-07-01T00:00:00Z',
                },
            ],
            assignable_roles: ['editor', 'viewer'],
        },
    },
    {
        match: /\/connected-accounts$/,
        data: {
            accounts: [
                {
                    id: 1,
                    provider: 'github',
                    name: 'Ada Lovelace',
                    nickname: 'ada',
                    email: 'ada@example.com',
                    avatar: null,
                    createdAt: '2026-06-01T09:00:00Z',
                },
            ],
            providers: [
                {
                    key: 'github',
                    label: 'GitHub',
                    icon: 'github',
                    color: '#181717',
                    linked: true,
                },
                {
                    key: 'google',
                    label: 'Google',
                    icon: 'google',
                    color: '#4285F4',
                    linked: false,
                },
            ],
            hasPassword: false,
        },
    },
    {
        match: /\/announcements$/,
        data: {
            unread: 2,
            announcements: [
                {
                    id: 1,
                    title: 'Dark mode is here 🌙',
                    body: 'Toggle it from the header — your choice is remembered across devices.',
                    level: 'feature',
                    publishedAt: '2026-06-26T10:00:00Z',
                    isNew: true,
                },
                {
                    id: 2,
                    title: 'Faster global search',
                    body: 'Spotlight now returns results roughly 3× quicker.',
                    level: 'feature',
                    publishedAt: '2026-06-22T10:00:00Z',
                    isNew: true,
                },
                {
                    id: 3,
                    title: 'Fixed CSV export edge case',
                    body: 'Quoted fields with embedded newlines now round-trip correctly.',
                    level: 'fix',
                    publishedAt: '2026-06-18T10:00:00Z',
                    isNew: false,
                },
            ],
        },
    },
    {
        match: /\/saved-views(\?|$)/,
        data: {
            views: [
                { id: 1, name: 'All products', state: {}, isDefault: false },
                { id: 2, name: 'Active', state: {}, isDefault: true },
                { id: 3, name: 'Low stock', state: {}, isDefault: false },
            ],
        },
    },
    {
        match: /\/tags(\?|$)/,
        data: { tags: ['laravel', 'vue', 'inertia', 'shadcn'] },
    },
    {
        match: /\/notification-preferences$/,
        data: {
            channels: [
                { key: 'mail', label: 'Email' },
                { key: 'database', label: 'In-app' },
                { key: 'broadcast', label: 'Push' },
            ],
            types: [
                {
                    key: 'orders',
                    label: 'Order updates',
                    channels: { mail: true, database: true, broadcast: true },
                },
                {
                    key: 'mentions',
                    label: 'Mentions & replies',
                    channels: { mail: false, database: true, broadcast: true },
                },
                {
                    key: 'marketing',
                    label: 'Marketing & tips',
                    channels: { mail: false, database: true, broadcast: false },
                },
            ],
        },
    },
    {
        match: /\/comments(\?|$)/,
        data: {
            comments: [
                {
                    id: 1,
                    body: 'This looks great — ship it! 🚀',
                    authorId: 1,
                    authorName: 'Ada Lovelace',
                    authorAvatar: null,
                    parentId: null,
                    createdAt: '2026-06-26T10:00:00Z',
                    edited: false,
                    editable: true,
                    replies: [
                        {
                            id: 2,
                            body: "Agreed. I'll review the tests this afternoon.",
                            authorId: 2,
                            authorName: 'Grace Hopper',
                            authorAvatar: null,
                            parentId: 1,
                            createdAt: '2026-06-26T10:30:00Z',
                            edited: false,
                            editable: false,
                            replies: [],
                        },
                    ],
                },
                {
                    id: 3,
                    body: 'One nit: can we rename this field?',
                    authorId: 2,
                    authorName: 'Grace Hopper',
                    authorAvatar: null,
                    parentId: null,
                    createdAt: '2026-06-26T11:15:00Z',
                    edited: true,
                    editable: false,
                    replies: [],
                },
            ],
        },
    },
    {
        match: /\/sessions$/,
        data: {
            sessions: [
                {
                    id: 'a1',
                    ipAddress: '203.0.113.10',
                    browser: 'Chrome',
                    platform: 'macOS',
                    device: 'desktop',
                    isCurrentDevice: true,
                    lastActive: '2026-06-26T10:00:00Z',
                },
                {
                    id: 'b2',
                    ipAddress: '198.51.100.4',
                    browser: 'Safari',
                    platform: 'iOS',
                    device: 'mobile',
                    isCurrentDevice: false,
                    lastActive: '2026-06-25T18:30:00Z',
                },
                {
                    id: 'c3',
                    ipAddress: '192.0.2.7',
                    browser: 'Firefox',
                    platform: 'Windows',
                    device: 'desktop',
                    isCurrentDevice: false,
                    lastActive: '2026-06-20T09:15:00Z',
                },
            ],
            databaseDriver: true,
            requiresPassword: true,
        },
    },
    {
        match: /\/onboarding$/,
        data: {
            steps: [
                {
                    key: 'verify-email',
                    title: 'Verify your email',
                    description: 'Confirm your address to unlock everything.',
                    ctaLabel: 'Resend',
                    ctaHref: '#',
                    icon: 'mail',
                    completed: true,
                    manual: false,
                },
                {
                    key: 'invite',
                    title: 'Invite a teammate',
                    description: 'Collaboration is better together.',
                    ctaLabel: 'Invite',
                    ctaHref: '#',
                    icon: 'user',
                    completed: false,
                    manual: false,
                },
                {
                    key: 'read-docs',
                    title: 'Read the quickstart',
                    description: null,
                    ctaLabel: null,
                    ctaHref: null,
                    icon: null,
                    completed: false,
                    manual: true,
                },
            ],
            completedCount: 1,
            total: 3,
            complete: false,
            dismissed: false,
        },
    },
    {
        match: /\/report-types$/,
        data: [
            {
                token: 'tok_monthly_invoices',
                label: 'Monthly Invoices',
                description: 'Every invoice issued, with line-item totals.',
                format: 'xlsx',
            },
            {
                token: 'tok_customer_export',
                label: 'Customer Export',
                description:
                    'All customers with contact details and lifetime value.',
                format: 'csv',
            },
            {
                token: 'tok_order_audit',
                label: 'Order Audit Trail',
                description: null,
                format: 'csv',
            },
        ],
    },
    {
        match: /\/report-runs$/,
        data: {
            heading: null,
            description: null,
            poll: null,
            isStriped: false,
            model: 'token',
            columns: [
                col('report', { label: 'Report' }),
                col('status', { label: 'Status', isBadge: true }),
                col('rows', { label: 'Rows', alignment: 'right' }),
                col('percent', { label: 'Progress', type: 'progress' }),
                col('format', { label: 'Format' }),
                col('created', { label: 'Created' }),
            ],
            filters: [],
            recordActions: [],
            toolbarActions: [],
            bulkActions: [],
            footerActions: [],
            records: [
                {
                    id: 1,
                    values: {
                        report: 'Monthly Invoices',
                        status: 'Completed',
                        rows: '4,820',
                        percent: 100,
                        format: 'xlsx',
                        created: '2 minutes ago',
                    },
                    icons: {},
                    iconColors: {},
                    badgeColors: { status: 'success' },
                    progress: { percent: 100 },
                    progressColors: { percent: 'success' },
                    viewProps: {},
                    descriptions: {},
                    recordUrl: null,
                    actions: [
                        {
                            name: 'download',
                            label: 'Download',
                            icon: 'download',
                            iconPosition: 'before',
                            url: '#',
                            shouldOpenInNewTab: false,
                            color: 'primary',
                            size: 'sm',
                            viewType: 'button',
                            shouldClose: false,
                            shouldMarkAsRead: false,
                            shouldMarkAsUnread: false,
                            requiresConfirmation: false,
                            type: 'action',
                            isIconButton: true,
                        },
                    ],
                },
                {
                    id: 2,
                    values: {
                        report: 'Customer Export',
                        status: 'Running',
                        rows: '1,204',
                        percent: 42,
                        format: 'csv',
                        created: '10 minutes ago',
                    },
                    icons: {},
                    iconColors: {},
                    badgeColors: { status: 'info' },
                    progress: { percent: 42 },
                    progressColors: { percent: 'info' },
                    viewProps: {},
                    descriptions: {},
                    recordUrl: null,
                    actions: [
                        {
                            name: 'cancel',
                            label: 'Cancel',
                            icon: 'x',
                            iconPosition: 'before',
                            url: '#',
                            shouldOpenInNewTab: false,
                            color: 'danger',
                            size: 'sm',
                            viewType: 'button',
                            shouldClose: false,
                            shouldMarkAsRead: false,
                            shouldMarkAsUnread: false,
                            requiresConfirmation: true,
                            type: 'action',
                            isIconButton: true,
                        },
                    ],
                },
                {
                    id: 3,
                    values: {
                        report: 'Order Audit Trail',
                        status: 'Failed',
                        rows: '380',
                        percent: null,
                        format: 'csv',
                        created: '1 hour ago',
                    },
                    icons: {},
                    iconColors: {},
                    badgeColors: { status: 'danger' },
                    progress: { percent: null },
                    progressColors: {},
                    viewProps: {},
                    descriptions: {},
                    recordUrl: null,
                    actions: [
                        {
                            name: 'retry',
                            label: 'Retry',
                            icon: 'rotate-ccw',
                            iconPosition: 'before',
                            url: '#',
                            shouldOpenInNewTab: false,
                            color: 'primary',
                            size: 'sm',
                            viewType: 'button',
                            shouldClose: false,
                            shouldMarkAsRead: false,
                            shouldMarkAsUnread: false,
                            requiresConfirmation: false,
                            type: 'action',
                            isIconButton: true,
                        },
                    ],
                },
                {
                    id: 4,
                    values: {
                        report: 'Monthly Invoices',
                        status: 'Cancelled',
                        rows: '92',
                        percent: null,
                        format: 'xlsx',
                        created: 'Yesterday',
                    },
                    icons: {},
                    iconColors: {},
                    badgeColors: { status: 'gray' },
                    progress: { percent: null },
                    progressColors: {},
                    viewProps: {},
                    descriptions: {},
                    recordUrl: null,
                    actions: [
                        {
                            name: 'retry',
                            label: 'Retry',
                            icon: 'rotate-ccw',
                            iconPosition: 'before',
                            url: '#',
                            shouldOpenInNewTab: false,
                            color: 'primary',
                            size: 'sm',
                            viewType: 'button',
                            shouldClose: false,
                            shouldMarkAsRead: false,
                            shouldMarkAsUnread: false,
                            requiresConfirmation: false,
                            type: 'action',
                            isIconButton: true,
                        },
                    ],
                },
            ],
            isPaginated: false,
            paginationPageOptions: [10],
            pagination: null,
            state: {
                search: '',
                sort: '',
                direction: 'asc',
                filters: {},
                perPage: 10,
            },
            queryPrefix: '',
            summaries: {},
            hasSummaries: false,
            reorderable: false,
            savedViewsKey: null,
        },
    },
    {
        match: /\/report-schedules$/,
        data: {
            heading: null,
            description: null,
            poll: null,
            isStriped: false,
            model: 'token',
            columns: [
                col('report', { label: 'Report' }),
                col('frequency', { label: 'Frequency' }),
                col('enabled', { label: 'Enabled', type: 'toggle-input' }),
                col('next_run_at', { label: 'Next run' }),
                col('last_run_at', { label: 'Last run' }),
            ],
            filters: [],
            recordActions: [],
            toolbarActions: [],
            bulkActions: [],
            footerActions: [],
            records: [
                {
                    id: 1,
                    values: {
                        report: 'Monthly Invoices',
                        frequency: 'monthly',
                        enabled: true,
                        next_run_at: 'Aug 1, 2026',
                        last_run_at: 'Jul 1, 2026',
                    },
                    icons: {},
                    iconColors: {},
                    badgeColors: {},
                    progress: {},
                    progressColors: {},
                    viewProps: {},
                    descriptions: {},
                    recordUrl: null,
                    actions: [],
                },
                {
                    id: 2,
                    values: {
                        report: 'Customer Export',
                        frequency: 'weekly',
                        enabled: true,
                        next_run_at: 'Jul 19, 2026',
                        last_run_at: 'Jul 12, 2026',
                    },
                    icons: {},
                    iconColors: {},
                    badgeColors: {},
                    progress: {},
                    progressColors: {},
                    viewProps: {},
                    descriptions: {},
                    recordUrl: null,
                    actions: [],
                },
            ],
            isPaginated: false,
            paginationPageOptions: [10],
            pagination: null,
            state: {
                search: '',
                sort: '',
                direction: 'asc',
                filters: {},
                perPage: 10,
            },
            queryPrefix: '',
            summaries: {},
            hasSummaries: false,
            reorderable: false,
            savedViewsKey: null,
        },
    },
    {
        match: /\/tables\/relations\/record\/resolve$/,
        data: {
            form: {
                schema: [{ type: 'text-input', name: 'title', label: 'Title' }],
                data: { title: 'Ship the audit' },
                rules: {},
                operation: 'edit',
            },
            infolist: {
                columns: 1,
                schema: [
                    {
                        type: 'text',
                        name: 'title',
                        label: 'Title',
                        state: 'Ship the audit',
                    },
                ],
            },
        },
    },
    {
        match: /\/tables\/relations\/(attachable|associable)$/,
        data: {
            options: [
                { id: 1, label: 'php' },
                { id: 2, label: 'vue' },
            ],
        },
    },
    {
        match: /\/tables\/relations\/(attach|detach|associate|dissociate)$/,
        data: { status: 'success' },
    },
];

export async function kinetixFetch<T = unknown>(
    url: string,
    init?: { method?: string; body?: unknown },
): Promise<T | null> {
    // Recorded so browser (Playwright) assertions can verify which endpoint a
    // click actually fired, with what payload.
    const g = globalThis as unknown as {
        __kinetixCalls?: Array<{ url: string; body: unknown }>;
    };
    (g.__kinetixCalls ??= []).push({ url, body: init?.body ?? null });

    const hit = fixtures.find((f) => f.match.test(url));
    return (hit ? (hit.data as T) : null) ?? null;
}

export function kinetixRoutePrefix(): string {
    return '_kinetix';
}

export function xsrfToken(): string {
    return 'gallery-stub-token';
}
